/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    fontFamily: {
      sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      mono: ['JetBrains Mono', 'Fira Code', 'SF Mono', 'monospace'],
      display: ['Playfair Display', 'Georgia', 'serif'],
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        'border-subtle': 'hsl(var(--border-subtle))',
        'border-strong': 'hsl(var(--border-strong))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        'text-secondary': 'hsl(var(--text-secondary))',
        'text-muted': 'hsl(var(--text-muted))',
        'text-placeholder': 'hsl(var(--text-placeholder))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          dark: 'hsl(var(--primary-dark))',
          light: 'hsl(var(--primary-light))',
          lighter: 'hsl(var(--primary-lighter))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
          orange: 'hsl(var(--accent-orange))',
          hover: 'hsl(var(--accent-hover))',
          light: 'hsl(var(--accent-light))',
          subtle: 'hsl(var(--accent-subtle))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        gold: {
          DEFAULT: 'hsl(var(--gold))',
          light: 'hsl(var(--gold-light))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          bg: 'hsl(var(--success-bg))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          bg: 'hsl(var(--warning-bg))',
        },
        danger: {
          DEFAULT: 'hsl(var(--danger))',
          bg: 'hsl(var(--danger-bg))',
        },
        info: {
          DEFAULT: 'hsl(var(--info))',
          bg: 'hsl(var(--info-bg))',
        },
        sidebar: {
          bg: 'hsl(var(--sidebar-bg))',
          hover: 'hsl(var(--sidebar-hover))',
          active: 'hsl(var(--sidebar-active))',
        },
        surface: 'hsl(var(--surface))',
        'surface-hover': 'hsl(var(--surface-hover))',
      },
      borderRadius: {
        sm: '6px',
        md: '10px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        sidebar: '260px',
        'sidebar-collapsed': '72px',
        topbar: '64px',
      },
      fontSize: {
        '4xl': ['36px', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.5px' }],
        '3xl': ['28px', { lineHeight: '1.2', fontWeight: '800', letterSpacing: '-0.5px' }],
        '2xl': ['24px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.3px' }],
        xl: ['20px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '-0.2px' }],
        lg: ['16px', { lineHeight: '1.4', fontWeight: '600' }],
        md: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        base: ['13.5px', { lineHeight: '1.6', fontWeight: '400' }],
        sm: ['12px', { lineHeight: '1.5', fontWeight: '500' }],
        xs: ['11px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.5px', textTransform: 'uppercase' }],
      },
      boxShadow: {
        sm: '0 1px 2px rgba(10, 37, 64, 0.04)',
        md: '0 4px 12px rgba(10, 37, 64, 0.08)',
        lg: '0 8px 24px rgba(10, 37, 64, 0.12)',
        xl: '0 16px 48px rgba(10, 37, 64, 0.16)',
        'glow-orange': '0 0 20px rgba(232, 106, 51, 0.2)',
        'glow-blue': '0 0 20px rgba(41, 128, 185, 0.15)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.4', transform: 'scale(0.8)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-100% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'skeleton-shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in-up': 'fade-in-up 0.5s ease-out',
        'pulse-dot': 'pulse-dot 2s infinite ease-in-out',
        shimmer: 'shimmer 1.5s infinite',
        'skeleton-shimmer': 'skeleton-shimmer 1.5s infinite',
        'spin-slow': 'spin 1s linear infinite',
      },
      transitionDuration: {
        fast: '150ms',
        base: '250ms',
        slow: '350ms',
        bounce: '400ms',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      screens: {
        'desktop-xl': '1280px',
        desktop: '1024px',
        tablet: '768px',
        mobile: '480px',
      },
    },
  },
  plugins: [],
};
