"""add_notification_preferences_to_users

Revision ID: 00c35cf85ccb
Revises: bb25b3baf793
Create Date: 2026-08-14 08:47:33.120062
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '00c35cf85ccb'
down_revision: Union[str, None] = 'bb25b3baf793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('summary_frequency', sa.String(length=20), nullable=False, server_default='diario'))
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'summary_frequency')
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###
