"""initial sqlite schema

Revision ID: bb25b3baf793
Revises: 
Create Date: 2026-08-11 09:04:41.985156
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bb25b3baf793'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industrial_sectores',
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('alerts',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletins',
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=True),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitiveness_indices',
    sa.Column('sector', sa.String(length=200), nullable=False),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('indicador', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('fuente', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicators',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_code'), 'indicators', ['code'], unique=True)
    op.create_table('organizations',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('siglas', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('email_contacto', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siglas')
    )
    op.create_table('patent_map_entries',
    sa.Column('tecnologia', sa.String(length=200), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('total_patentes', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('tendencia', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulations',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('regulation_number', sa.String(length=50), nullable=False),
    sa.Column('issuing_body', sa.String(length=200), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulations_regulation_number'), 'regulations', ['regulation_number'], unique=True)
    op.create_table('technologies',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('trl_nivel', sa.Integer(), nullable=True),
    sa.Column('referencia_ontologia', sa.String(length=50), nullable=True),
    sa.Column('palabras_clave', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('follower_type', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'follower_type', 'organization_id', name='uq_follow')
    )
    op.create_table('patents',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('patent_number', sa.String(length=50), nullable=False),
    sa.Column('applicant', sa.String(length=200), nullable=False),
    sa.Column('inventor', sa.String(length=200), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('technological_sector', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_patent_number'), 'patents', ['patent_number'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('grado_cientifico', sa.String(length=50), nullable=True),
    sa.Column('cv_url', sa.String(length=255), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('intereses', sa.JSON(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('researchgate_url', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_profiles_user_id'), 'professional_profiles', ['user_id'], unique=True)
    op.create_table('research_publications',
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('autores', sa.Text(), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('journal', sa.String(length=200), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('palabras_clave', sa.JSON(), nullable=True),
    sa.Column('sector_codigo', sa.String(length=3), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sector_codigo'], ['industrial_sectores.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_publications')
    op.drop_index(op.f('ix_professional_profiles_user_id'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patents_patent_number'), table_name='patents')
    op.drop_table('patents')
    op.drop_table('follows')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_regulations_regulation_number'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_table('patent_map_entries')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_indicators_code'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_table('competitiveness_indices')
    op.drop_table('bulletins')
    op.drop_table('alerts')
    op.drop_table('industrial_sectores')
    # ### end Alembic commands ###
