"""Organization-to-organization follow relationships.

Auto-generated by FollowService. Do not edit manually —
the file is regenerated on every follow/unfollow API call.
"""

FOLLOWS_DATA: list[tuple[str, str]] = [
]
